name: fedenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37he5f6b98_1008
  - cryptography=3.1.1=py37hff6837a_1
  - cudatoolkit=10.2.89=hfd86e86_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py37h14c3975_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - notebook=5.7.8=py37_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=py_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.2.4=py37_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pyzmq=19.0.2=py37he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - send2trash=1.5.0=py37_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.1=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tornado=4.5.3=py37_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.10.0
    - aioice==0.6.18
    - aiortc==0.9.28
    - astor==0.8.1
    - astunparse==1.6.3
    - av==8.0.2
    - cachetools==4.1.1
    - click==7.1.2
    - crc32c==2.2
    - cycler==0.10.0
    - dill==0.3.2
    - docopt==0.6.2
    - flask==1.1.2
    - flask-socketio==4.2.1
    - flatbuffers==1.12
    - gast==0.2.2
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - humanize==3.1.0
    - idna==2.8
    - imageio==2.9.0
    - importlib-resources==1.5.0
    - install==1.3.4
    - itsdangerous==1.1.0
    - joblib==0.17.0
    - jupyter-tensorboard==0.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lz4==3.0.2
    - markdown==3.3.2
    - matplotlib==3.3.2
    - msgpack==1.0.0
    - netifaces==0.10.9
    - networkx==2.5
    - nibabel==3.2.0
    - numpy==1.18.1
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - openmined-threepio==0.2.0
    - opt-einsum==3.3.0
    - pandas==1.1.4
    - pathlib==1.0.1
    - phe==1.4.0
    - protobuf==3.14.0
    - psutil==5.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyee==8.1.0
    - pykwalify==1.7.0
    - pylibsrtp==0.6.7
    - pyradiomics==3.0.1
    - python-deprecated==1.1.0
    - python-engineio==3.13.2
    - python-socketio==4.6.0
    - pytz==2020.1
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - restrictedpython==5.1
    - rsa==4.6
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - seaborn==0.11.0
    - shaloop==0.2.1-alpha.11
    - simpleitk==1.2.4
    - sklearn==0.0
    - syft==0.2.9
    - syft-proto==0.5.2
    - tblib==1.6.0
    - tensorboard==1.15.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==1.15.4
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - tf-encrypted==0.5.9
    - threadpoolctl==2.1.0
    - tifffile==2020.11.18
    - torch==1.4.0
    - torchio==0.18.28
    - torchvision==0.5.0
    - tqdm==4.51.0
    - websocket-client==0.57.0
    - websockets==8.1
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /home/linardos/anaconda3/envs/fedenv
